# Asssingment 03
## Question 01- Online Passive Aggressive Algorithm
## Index Number - 17000475
### Youtube Link -

## Terms used in journal paper
w - Vector of weights (w ∈ Rn) 

n_iter - number of iteration 

c- aggressiveness parameter (regression)

(x,y) - instance label pair  y is + or -

|w.x| - Degree of confidence

y(w.x) - Signed Margin

Goal of algorithm - achive an margin of at least 1

hinge-loss (when algorithm get margin less than 1) - loss(w,(x,y)) = if y(w.x) >=1 then 0 else 1-y(w.x)





## Binary Classification Algorithms
There are three variants . Three different way of updating the rule of weight vector.

All three variants initialized w vector to zero.

wt+1 = argmin (1/2(|w-wt|)^2) s.t loss(w,(x,y)) = 0

Another way to express this same update rule is ,

wt+1 = wt + (tor) x (yt) x (xt)  where tor = loss_t / |xt|^2 (accroding to PA)

loss_t is hinge loss which gives as loss(w,(x,y))

### Passive is when hinge loss is 0 and aggressive when hinge loss is positive.

## Task 2 : Implementation of Passive Agressive algorithm for classification

In [1]:
#  torr = loss_t / |xt|^2 (accroding to PA)
def passive_aggressive(hinge_loss,xsquare,c=None):
    return hinge_loss/ xsquare

In [2]:
# PA varinat 1
def passive_aggressive_1(hinge_loss,xsquare,c):
    return min([c,hinge_loss/xsquare])

In [3]:
# PA variant 2
def passive_aggressive_2(hinge_loss,xsquare,c):
    return hinge_loss/(xsquare+1/(2*c))
  

In [ ]:
'''
Parameters : 
X- matrix with features
y- matrix with classes
update_rule - name of variant of update rule
c -

'''

def PA_algorithm(X,Y,update_rule,n_iter=1,c=None):
    w= np.zeros(X.shape[1])                  # initialize as 0
    for j in range(n_iter):    
        for i in range(0,X.shape[0]):                # each instanse
            xsquare =  np.dot(X[i],X[i].T)
            #print(1- Y[i]*(np.dot(w.T,X[i])))
            hinge_loss = max(0,1-Y[i]*np.dot(w.T,X[i]))
            #print('hinge_loss',hinge_loss)
            torr = update_rule(hinge_loss,xsquare,c)             # PA or PA I or PA II  
            #print("torr ",torr)
            w = w + torr*Y[i]*X[i]                # update
            #print(type(torr*Y[i]*X[i]))
            #print('w ',w)
    return w
    

## Task 3 : Preparing the dataset
## Breast Cancer Dataset
Since breast cancer dataset is used for binary classification task we will use classification algorithm. 
bengin (2) reflect -1 which says no cancer and malignant (4) +1 which says there is a cancer.

In [4]:
# import modules
import numpy as np 
import pandas as pd 


In [11]:
# read dataset
data = pd.read_csv('datafile.csv',header=None)
data.head()

0   1   2   3   4   5   6   7   8   9   10
0  1000025   5   1   1   1   2   1   3   1   1   2
1  1002945   5   4   4   5   7  10   3   2   1   2
2  1015425   3   1   1   1   2   2   3   1   1   2
3  1016277   6   8   8   1   3   4   3   7   1   2
4  1017023   4   1   1   3   2   1   3   1   1   2

In [12]:
# find ? mark 
data[data.eq("?").any(1)]

0   1   2   3   4   5  6   7   8   9   10
23   1057013   8   4   5   1   2  ?   7   3   1   4
40   1096800   6   6   6   9   6  ?   7   8   1   2
139  1183246   1   1   1   1   1  ?   2   1   1   2
145  1184840   1   1   3   1   2  ?   2   1   1   2
158  1193683   1   1   2   1   3  ?   1   1   1   2
164  1197510   5   1   1   1   2  ?   3   1   1   2
235  1241232   3   1   4   1   2  ?   3   1   1   2
249   169356   3   1   1   1   2  ?   3   1   1   2
275   432809   3   1   3   1   2  ?   2   1   1   2
292   563649   8   8   8   1   2  ?   6  10   1   4
294   606140   1   1   1   1   2  ?   2   1   1   2
297    61634   5   4   3   1   2  ?   2   3   1   2
315   704168   4   6   5   6   7  ?   4   9   1   2
321   733639   3   1   1   1   2  ?   3   1   1   2
411  1238464   1   1   1   1   1  ?   2   1   1   2
617  1057067   1   1   1   1   1  ?   1   1   1   2

In [13]:
 #replace ? mark  with 0
 data = data.replace(["?"],0)

In [14]:
#check whether it's removed
data[data.eq("?").any(1)]

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Index: []

In [15]:
# drop id column
data.drop([0],axis=1,inplace = True)

In [17]:
data.head()

1   2   3   4   5   6   7   8   9   10
0   5   1   1   1   2   1   3   1   1   2
1   5   4   4   5   7  10   3   2   1   2
2   3   1   1   1   2   2   3   1   1   2
3   6   8   8   1   3   4   3   7   1   2
4   4   1   1   3   2   1   3   1   1   2

In [18]:
data[10]

0      2
1      2
2      2
3      2
4      2
      ..
694    2
695    2
696    4
697    4
698    4
Name: 10, Length: 699, dtype: int64

In [19]:
# replace class column 10 th column 2, 4 value with -1 and, +1
data[10] = data[10].map({2:-1,4:+1})
data[10]

0     -1
1     -1
2     -1
3     -1
4     -1
      ..
694   -1
695   -1
696    1
697    1
698    1
Name: 10, Length: 699, dtype: int64

In [20]:
X = data[:].drop(10,axis=1).to_numpy(dtype='int')
print(X)
print(X.shape)
Y = data[:].pop(10).to_numpy(dtype='int')
print(Y)
print(Y.shape)

[[ 5  1  1 ...  3  1  1]
 [ 5  4  4 ...  3  2  1]
 [ 3  1  1 ...  3  1  1]
 ...
 [ 5 10 10 ...  8 10  2]
 [ 4  8  6 ... 10  6  1]
 [ 4  8  8 ... 10  4  1]]
(699, 9)
[-1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1  1  1 -1 -1  1 -1  1  1 -1  1
 -1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1  1 -1  1  1 -1  1  1  1  1 -1  1 -1
 -1  1  1  1  1  1  1  1  1  1  1  1  1 -1  1  1 -1  1 -1  1  1 -1 -1  1
 -1  1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1  1  1  1  1 -1  1  1  1  1  1 -1  1 -1  1  1  1 -1 -1 -1  1 -1 -1
 -1 -1  1  1  1 -1  1 -1  1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1  1 -1
 -1 -1  1 -1 -1  1 -1  1  1 -1 -1  1 -1 -1 -1  1  1 -1 -1 -1 -1 -1  1  1
 -1 -1 -1 -1 -1  1  1  1 -1  1 -1  1 -1 -1 -1  1  1 -1  1  1  1 -1  1  1
 -1 -1 -1 -1 -1 -1 -1 -1  1  1 -1 -1 -1  1  1 -1 -1 -1  1  1 -1  1  1  1
 -1 -1  1 -1 -1  1  1  1  1 -1  1  1 -1  1  1  1 -1  1 -1 -1  1  1  1  1
 -1 -1 -1 -1 -1 -1  1  1 -1 -1 -1  1 -1  1  1  1 -1 -1 -1 -1  1  1  1  1
  1 -1  1  1  1 -1  1 -1  1  1 -

## Task 4 : Apply classifier on Breast cancer dataset 
## PA I and PA II Implementation

In [86]:
(100*1)/3

33.333333333333336

In [21]:
# Training and Testing set split
data_copy = data.copy()
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33,random_state=200)
# X_train = data.sample(frac=0.7, random_state=0)
# X_test = data.drop(X_train.index)

# Y_train = X_train.pop([10])
# Y_test = X_test.pop([10])

In [22]:
print(X_train.shape, Y_train.shape)
print(X_test.shape, Y_test.shape)

(468, 9) (468,)
(231, 9) (231,)


## Training

In [177]:
#np.power(np.linalg.norm(xt, ord=2), 2)

44.0

## PA variant

In [27]:
# Training 
w = PA_algorithm(X_train,Y_train,passive_aggressive)

## Results

In [28]:
# Compute accuracy of training set
Y_train_pred = np.sign(np.dot(w.T, X_train.T))
count = np.count_nonzero(Y_train_pred + Y_train) # correct count

print('PA Train accuracy: {}'.format(float(count) / X_train.shape[0]))

PA Train accuracy: 0.6987179487179487


In [29]:
# Compute accuracy of test set
Y_pred = np.sign(np.dot(w.T, X_test.T))
c = np.count_nonzero(Y_pred + Y_test)   # correct count

print('PA Test accuracy: {}'.format( float(c) / X_test.shape[0]))

PA Test accuracy: 0.7142857142857143


## PA I variant

In [32]:
for n_iter in [1,2,10]:
    # Training 
    w = PA_algorithm(X_train,Y_train,passive_aggressive_1,n_iter,c=1)
    # Compute accuracy of training set
    Y_train_pred = np.sign(np.dot(w.T, X_train.T))
    count = np.count_nonzero(Y_train_pred + Y_train) # correct count
    print('Iteration -',n_iter)
    print('PA I Train accuracy: {}'.format(float(count) / X_train.shape[0]))

    # Compute accuracy of test set
    Y_pred = np.sign(np.dot(w.T, X_test.T))
    c = np.count_nonzero(Y_pred + Y_test)   # correct count
    print('PA I Test accuracy: {}'.format( float(c) / X_test.shape[0]))

Iteration - 1
PA I Train accuracy: 0.6987179487179487
PA I Test accuracy: 0.7142857142857143
Iteration - 2
PA I Train accuracy: 0.7264957264957265
PA I Test accuracy: 0.7316017316017316
Iteration - 10
PA I Train accuracy: 0.7329059829059829
PA I Test accuracy: 0.7359307359307359


## PA II variant

In [33]:
for n_iter in [1,2,10]:
    # Training 
    w = PA_algorithm(X_train,Y_train,passive_aggressive_2,n_iter,c=1)
    # Compute accuracy of training set
    Y_train_pred = np.sign(np.dot(w.T, X_train.T))
    count = np.count_nonzero(Y_train_pred + Y_train) # correct count
    print('Iteration -',n_iter)
    print('PA II Train accuracy: {}'.format(float(count) / X_train.shape[0]))

    # Compute accuracy of test set
    Y_pred = np.sign(np.dot(w.T, X_test.T))
    c = np.count_nonzero(Y_pred + Y_test)   # correct count

    print('PA II Test accuracy: {}'.format( float(c) / X_test.shape[0]))

Iteration - 1
PA II Train accuracy: 0.7072649572649573
PA II Test accuracy: 0.7186147186147186
Iteration - 2
PA II Train accuracy: 0.7264957264957265
PA II Test accuracy: 0.7359307359307359
Iteration - 10
PA II Train accuracy: 0.7350427350427351
PA II Test accuracy: 0.7402597402597403


## Conclusion

PA II variant gave  imporvemnet in test accuracy over PA I varinat. Overall in all variants test accuracy is greater than train accuracy. This can happen due to distribution issue in the dataset occur with class imbalance in train test split. When spliting test and train datasets I have used shuffle = True default in train_test_spilt_funtion(). 