# Asssingment 03
## Question 02- ID3 and SVM algorithms
## Index Number - 17000475

In [1]:
import numpy as np 
import pandas as pd 
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score, roc_curve, roc_auc_score
from sklearn.model_selection import train_test_split
from keras.datasets import cifar10

from sklearn.svm import SVC
from sklearn.linear_model import SGDClassifier
from sklearn import tree

# Cifar Dataset Preparing

In [3]:
# load data
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

In [4]:
x_train.shape

(50000, 32, 32, 3)

In [4]:
#normalize data
x_train  = x_train/255
x_test  = x_test/255

In [5]:
x_train = np.reshape(x_train, (x_train.shape[0], -1))
x_test = np.reshape(x_test, (x_test.shape[0], -1))

In [19]:
y_train = y_train.reshape((-1,))

In [21]:
y_train.shape

(50000,)

In [18]:
x_train.shape

(50000, 3072)

In [22]:
# labeles 
labels = ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']

# Apply ID3 and SVM to Cifar dataset

In [6]:
# ID3
model_cifar_id3 = tree.DecisionTreeClassifier(criterion='entropy',splitter='best')
model_cifar_id3.fit(x_train,y_train)
y_pred_id3 = model_cifar_id3.predict(x_test)
print(f"Id3 model accuracy for Cifar dataset= {accuracy_score(y_test, y_pred_id3)}")

Id3 model accuracy for Cifar dataset= 0.2649


Same amount accuracy has got in this paper http://athena.ecs.csus.edu/~hoangkh/Image%20Classification%20with%20Fashion-MNIST%20and%20CIFAR-10%20-%20Final%20Report.pdf

In [23]:
from sklearn import  metrics
print("Classification report for classifier %s:\n%s\n"
      % (model_cifar_id3, metrics.classification_report(y_test, y_pred_id3)))


Classification report for classifier DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best'):
              precision    recall  f1-score   support

           0       0.34      0.34      0.34      1000
           1       0.30      0.28      0.29      1000
           2       0.20      0.21      0.21      1000
           3       0.16      0.16      0.16      1000
           4       0.21      0.21      0.21      1000
           5       0.23      0.22      0.22      1000
           6       0.29      0.28      0.28      1000
           7       0.25      0.26      0.26      1000
           8       0.37      0.39      0.38  

In [ ]:
# tree.plot_tree(model_cifar_id3)

In [7]:
y_train.shape

(50000, 1)

In [23]:
# SVM
# coudn't run within feasinble amount of time
model_cifar_svm = SVC(kernel='rbf', random_state = 1)
model_cifar_svm.fit(x_train,y_train)
y_pred_svm = model_cifar_svm.predict(x_test)
print(f"SVM model accuracy for Cifar Dataset= {accuracy_score(y_test, y_pred_svm)}")


In [ ]:
print("Classification report for classifier %s:\n%s\n"
      % (model_cifar_svm, metrics.classification_report(y_test, y_pred_svm)))


# Breast Cancer Dataset Preparing

In [3]:
df = pd.read_csv('datafile.csv',header = None)
df.head()

0   1   2   3   4   5   6   7   8   9   10
0  1000025   5   1   1   1   2   1   3   1   1   2
1  1002945   5   4   4   5   7  10   3   2   1   2
2  1015425   3   1   1   1   2   2   3   1   1   2
3  1016277   6   8   8   1   3   4   3   7   1   2
4  1017023   4   1   1   3   2   1   3   1   1   2

In [4]:
#replace ? mark  with 0
df = df.replace(["?"],0)
#check whether it's removed
df[df.eq("?").any(1)]

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Index: []

In [5]:
# drop id column
df.drop([0],axis=1,inplace = True)
# replace class column 10 th column 2, 4 value with -1 and, +1
df[10] = df[10].map({2:-1,4:+1})

In [6]:
X = df[:].drop(10,axis=1).to_numpy(dtype='int')
print(X)
print(X.shape)
Y = df[:].pop(10).to_numpy(dtype='int')
print(Y)
print(Y.shape)

[[ 5  1  1 ...  3  1  1]
 [ 5  4  4 ...  3  2  1]
 [ 3  1  1 ...  3  1  1]
 ...
 [ 5 10 10 ...  8 10  2]
 [ 4  8  6 ... 10  6  1]
 [ 4  8  8 ... 10  4  1]]
(699, 9)
[-1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1  1  1 -1 -1  1 -1  1  1 -1  1
 -1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1  1 -1  1  1 -1  1  1  1  1 -1  1 -1
 -1  1  1  1  1  1  1  1  1  1  1  1  1 -1  1  1 -1  1 -1  1  1 -1 -1  1
 -1  1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1  1  1  1  1 -1  1  1  1  1  1 -1  1 -1  1  1  1 -1 -1 -1  1 -1 -1
 -1 -1  1  1  1 -1  1 -1  1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1  1 -1
 -1 -1  1 -1 -1  1 -1  1  1 -1 -1  1 -1 -1 -1  1  1 -1 -1 -1 -1 -1  1  1
 -1 -1 -1 -1 -1  1  1  1 -1  1 -1  1 -1 -1 -1  1  1 -1  1  1  1 -1  1  1
 -1 -1 -1 -1 -1 -1 -1 -1  1  1 -1 -1 -1  1  1 -1 -1 -1  1  1 -1  1  1  1
 -1 -1  1 -1 -1  1  1  1  1 -1  1  1 -1  1  1  1 -1  1 -1 -1  1  1  1  1
 -1 -1 -1 -1 -1 -1  1  1 -1 -1 -1  1 -1  1  1  1 -1 -1 -1 -1  1  1  1  1
  1 -1  1  1  1 -1  1 -1  1  1 -

# Evaluation Metrics 

a. Accuracy

b. Sensitivity & Specificity

c. Precision & Recall

d. Confusion Matrix

e. F1 Score

f. ROC Curve

## SVM  Breast cancer dataset

In [7]:
# Train test split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33,random_state=200)

In [15]:
X_train.shape

(468, 9)

In [8]:

model_svm = SVC(kernel='rbf', random_state = 1)
model_svm.fit(X_train,Y_train)
Y_pred_svm = model_svm.predict(X_test)
print(Y_pred_svm)

[ 1  1  1  1  1 -1 -1  1 -1  1 -1  1 -1 -1 -1 -1 -1  1  1 -1 -1 -1 -1 -1
 -1 -1  1  1 -1 -1 -1 -1  1 -1 -1  1  1 -1 -1 -1  1 -1  1  1 -1  1  1  1
  1 -1 -1 -1 -1 -1 -1 -1  1  1 -1  1 -1 -1  1  1 -1 -1 -1 -1  1 -1  1 -1
 -1 -1 -1 -1  1 -1 -1 -1 -1  1 -1  1 -1 -1 -1 -1 -1  1 -1  1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  1 -1  1 -1  1  1  1 -1 -1 -1  1  1
  1 -1 -1 -1 -1  1  1 -1 -1  1  1 -1 -1 -1 -1  1 -1 -1  1  1 -1  1 -1  1
 -1  1 -1 -1 -1  1 -1  1 -1  1 -1 -1 -1  1  1  1 -1 -1 -1  1 -1 -1 -1 -1
  1  1 -1  1 -1 -1  1  1  1 -1  1  1 -1 -1 -1 -1 -1 -1  1  1  1  1  1 -1
 -1 -1 -1  1  1  1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1  1 -1 -1
 -1  1 -1 -1  1  1 -1  1  1 -1 -1  1 -1 -1 -1]


In [9]:
# a)
# Accuracy = TP/(TP+FN+FP+TP)
print(f"SVM model accuracy = {accuracy_score(Y_test, Y_pred_svm)}")

# b) 
# specificiry - True Negative rate   = TN / (FP + TN)          (1- False positive rate)
tn, fp, fn, tp = confusion_matrix(Y_test, Y_pred_svm).ravel()
specificity = tn / (tn+fp)
print(f"SVM model specificity = {specificity}")
#sensitivity  - True Positive rate = Recall = TP/(TP + FN)
print(f"SVM model Sensitivity = {recall_score(Y_test, Y_pred_svm)}")

#c)
# Precision = TP/(TP + FP)
print(f"SVM model Precision = {precision_score(Y_test, Y_pred_svm)}")
# Recall = TP/(TP + FN)
print(f"SVM model Recall = {recall_score(Y_test, Y_pred_svm)}")




# d)
print(f"SVM model confusion matrix = {confusion_matrix(Y_test, Y_pred_svm)}")

# e )
# F1 score = 2TP/(2TP + FP+ FN )  = 2*(precision * Recall)/ (precsion + recall)
print(f"SVM model F1-score = {f1_score(Y_test, Y_pred_svm)}")
# f)
# ROC - reciver operating characteristic curve
# plots True positive rate(precision) vs. False positive Rate(1-TNR) for each threshold we want to compare.
# does not depend on the class distribution
# shows the trade-off between sensitivity (TPR) and specificity (1 – FPR)
import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=[0,1],
        y=[0,1],
        name="TPR = FPR",
        line=dict(color="black", dash="dash")
    )
)

def PlotRocAuc(y_test, y_pred, color, model_name):
    fpr, tpr, thresholds = roc_curve(Y_test, Y_pred_svm)
    auc_score = roc_auc_score(Y_test,Y_pred_svm)
    fig.add_trace(
        go.Scatter(
            x=fpr,
            y=tpr,
            name=f"{model_name}(AUC={auc_score})",
            marker=dict(color=color)
        )
    )
    
PlotRocAuc(Y_test, Y_pred_svm, "green", "svm_clf")

fig.update_layout(title="ROC curve",
                  xaxis_title="False Positive Rate",
                  yaxis_title="True Positive Rate")

fig.show() 



SVM model accuracy = 0.9567099567099567
SVM model specificity = 0.9419354838709677
SVM model Sensitivity = 0.9868421052631579
SVM model Precision = 0.8928571428571429
SVM model Recall = 0.9868421052631579
SVM model confusion matrix = [[146   9]
 [  1  75]]
SVM model F1-score = 0.9375


## Apply ID3 Breast Cancer Dataset

In [10]:

model_id3=tree.DecisionTreeClassifier(criterion='entropy',splitter='best')
model_id3.fit(X_train,Y_train)
Y_pred_id3=model_id3.predict(X_test)

In [11]:
# a)
# Accuracy = TP/(TP+FN+FP+TP)
print(f"id3 model accuracy = {accuracy_score(Y_test, Y_pred_id3)}")

# b) 
# specificiry - True Negative rate   = TN / (FP + TN)
tn, fp, fn, tp = confusion_matrix(Y_test, Y_pred_id3).ravel()
specificity = tn / (tn+fp)
print(f"id3 model specificity = {specificity}")
#sensitivity  - True Positive rate = Recall = TP/(TP + FN)
print(f"id3 model Sensitivity = {recall_score(Y_test, Y_pred_id3)}")

# Precision = TP/(TP + FP)
print(f"id3 model Precision = {precision_score(Y_test, Y_pred_id3)}")
# Recall = TP/(TP + FN)
print(f"id3 model Recall = {recall_score(Y_test, Y_pred_id3)}")

# c)


# d)
print(f"id3 model confusion matrix = {confusion_matrix(Y_test, Y_pred_id3)}")

# e )
# F1 score = 2TP/(2TP + FP+ FN )  = 2*(precision * Recall)/ (precsion + recall)
print(f"id3 model F1 score = {f1_score(Y_test, Y_pred_id3)}")
# f)
# ROC - reciver operating characteristic curve
# plots True positive rate(precision) vs. False positive Rate(1-TNR) for each threshold we want to compare.

import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=[0,1],
        y=[0,1],
        name="TPR = FPR",
        line=dict(color="black", dash="dash")
    )
)

def PlotRocAuc(y_test, y_pred, color, model_name):
    fpr, tpr, thresholds = roc_curve(Y_test, Y_pred_id3)
    auc_score = roc_auc_score(Y_test,Y_pred_id3)
    fig.add_trace(
        go.Scatter(
            x=fpr,
            y=tpr,
            name=f"{model_name}(AUC={auc_score})",
            marker=dict(color=color)
        )
    )
    
PlotRocAuc(Y_test, Y_pred_id3, "green", "id3_clf")

fig.update_layout(title="ROC curve",
                  xaxis_title="False Positive Rate",
                  yaxis_title="True Positive Rate")

fig.show() 



id3 model accuracy = 0.9134199134199135
id3 model specificity = 0.9225806451612903
id3 model Sensitivity = 0.8947368421052632
id3 model Precision = 0.85
id3 model Recall = 0.8947368421052632
id3 model confusion matrix = [[143  12]
 [  8  68]]
id3 model F1 score = 0.8717948717948718
